# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST:  mysql 
---
apiVersion: v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  #this labels are related to dployment
  labels:
    component: frontend
    project: Expense
    tier: web
  spec:
    replicas: 2
    selector:
      matchLabels:
        component: frontend
        project: Expense
        tier: web
    templet:
      metadate:
        lables:
          component: mysql
          project: frontend
          tier: web
      spec: 
        containers:
          - name: frontend
            image: joindevops/frontend:v1.0
            envFrom:
            - configMapRef:
                name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalncer
  labels:
    name: frontend
    project: expe nse
    componet: frontend
    environment: dev
ports:
- protocol: TCP
  port: 80 #load balancer
  targetport: 80 #target port
  