kind: Pod
apiVersion: v1 
metadata:
  name: Pod
spec:
  containers:
  - name: nginx
    image: nginx
  - name: alma 
    image: almallinux:9
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']