apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    course: K8
    Trainer: Shivakumar
    jenkins.build.url: 'https://jenkins.daws.io.online'
spec:
  containers:
  - name: nginx
    image: nginx
   