apiVersion: v1
kind: Pod
metadata: env
    name: 
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20 hours' 
      