apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: frontend
    project: expense
    componet: frontend
    environmen  t: dev
  ports:
  - protocol: TCP
    port: 80 #load balancer
    targetport: 80 #target port
    
