apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  labels:
    name: frontend
    project: expense
    componet: frontend
    environment: dev
spec:
  continers:
    name: nginx
    image: nginx
    
