apiVersion: v1
kind: Service
metadata:
  name: ngnix-lb
spec:
type: LoadBalancer
  selector:
    name: frontend
    project: expense
    componet: frontend
    environment: dev
ports:
- protocol: TCP
  port: 80 #load balancer
  targetport: 80 #target port
  nodePort: 32761 #k8 recommendation