apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
#This labels belong to replicaset
  labels:
    app: nginx
    tier: frontend  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      
      # below is called pod definition
  template:
    metadata:
        app: nginx
        tier: frontend
        Project: some-project
    spec:
      containers:
        - name: nginx
          image: nginx:mainline-perl































