apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #this labels are related to dployment
  labels:
    app: nginx
    purpose: deployment
    tier: web 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extrakey: extra-value
    spec: 
      containers:
      - name: nginx
        image: nginx:stable-perl


    



