apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx  
    env:
    - name: course
      valueForm:
        configMapkeyRef:
          name: daws78s
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: daws78s
          key: trainer






  #   env:
  # - name: course
  #   valueFrom:
  #     configMapkeyRef:
  #       name: daw98s
  #       key:  course
  # - name: trainer
  #   valueFrom:
  #     configMapkeyRef:
  #       name: daw98s
  #       key:  trainer
