apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  envFrom:
  - configMapRef:
     name: daws93







  #   env:
  # - name: course
  #   valueFrom:
  #     configMapkeyRef:
  #       name: daw98s
  #       key:  course
  # - name: trainer
  #   valueFrom:
  #     configMapkeyRef:
  #       name: daw98s
  #       key:  trainer
