kind: Deployment
apiVersion: apps/v1
metadata: 
  name: nginx
  labels:
    app: nginx
    purpose: Deployment
    tier: web
  spec:
    replicas: 3
    selector:
      match labels:
        app: nginx
        purpose: Deployment
        tire: web
        project: some-project
    #pod defintion
    templet:
      metadata:
        lables:
          app: nginx
          purpose: Deployment
          tire: web
          project: some-project
      spec:
        containers:
        - name: nginx
          image: nginx
          
