kind: Deployment
apiVersion: v1
metadata:
  name: ngnix-Dep
  #this labels are related to dployment
  labels:
    app: nginx
    purpose: deployment
    tier: web-frontend  
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
        tier: web
        project: test-project
    templet:
      metadate:
        lables:
          app: nginx
          tier: web
          Project: some project
      spec: 
        containers:
          - name: nginx
            image: nginx


    

