apiVersion: v1
kind: Deployment
metadata:
  name: mysql
  #this labels are related to dployment
  labels:
    component: mysql
    project: Expense
    tier: database
  spec:
    replicas: 3
    selector:
      matchLabels:
        component: mysql
        project: Expense
        tier: database
    templet:
      metadate:
        lables:
          component: mysql
          project: Expense
          tier: database
      spec: 
        containers:
          - name: mysql
            image: joindevops/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  labels:
    name: db
    project: expense
    componet: db
    environment: dev
ports:
- protocol: TCP
  port: 3306 #load balancer
  targetport: 3306 #target port
  
    

    



