apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  labels:
    name: frontend
    project: expense
    componet: frontend
    environment: dev
ports:
- protocol: TCP
  port: 80 #load balancer
  targetport: 80 #target port
    