apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: always   #keep this always
  nodeselector:
    project: expense
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
