apiVersion: v1    ##pv
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-054b71440f7788059
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  labesl:
    purpose: ebs-Static
    project: expense
spec:
  containers:
  - name: nginx
    image: ngnix
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/ngnix/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-lb
spec:
  type: LoadBalancer
  selector:
    purpose: Ebs-Static
    project: expense
ports:
- protocol: TCP
  port: 80 #load balancer
  targetport: 80 #target port
  nodePort: 32761 #k8 recommendation