apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST:  mysql 
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  #this labels are related to dployment
  labels:
    component: backend
    project: Expense
    tier: app
  spec:
    replicas: 3
    selector:
      matchLabels:
        component: backend
        project: Expense
        tier: app
    templet:
      metadate:
        lables:
          component: mysql
          project: backend
          tier: app
      spec: 
        containers:
          - name: backend
            image: joindevops/backend:v1.0
            envFrom:
            - configMapRef:
                name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  labels:
    name: backend
    project: expense
    componet: backend
    environment: dev
ports:
- protocol: TCP
  port: 8080 #load balancer
  targetport: 8080 #target port
  
    

    



